import type { Metadata } from "next";
import { AppProvider } from "@/providers/AppProvider";
import { BootstrapGuard } from "@/features/bootstrap/components/BootstrapGuard";

import "../styles/globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({
  variable: "--font-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col"><AppProvider><BootstrapGuard>{children}</BootstrapGuard></AppProvider></body>
    </html>
  );
}
