export const generateOrderId = (admissionYear: string, branchId: string): string => {
  // In a real app, the sequence would be generated by the database to prevent race conditions.
  // We'll mock it here.
  const seq = Math.floor(Math.random() * 999) + 1;
  const seqString = seq.toString().padStart(3, '0');
  
  // Extract last two digits of admission year (e.g., "2025" -> "25")
  const shortYear = admissionYear.slice(-2);
  
  return `BLZ-${shortYear}-${branchId}-${seqString}`;
};
