// src/features/checkout/constants/index.ts

export const CHECKOUT_ERRORS = {
  NETWORK_OFFLINE: 'NETWORK_OFFLINE',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  CART_EMPTY: 'CART_EMPTY',
  PRICE_CHANGED: 'PRICE_CHANGED',
  COUPON_INVALID: 'COUPON_INVALID',
  ORDER_FAILED: 'ORDER_FAILED',
  UNKNOWN: 'UNKNOWN'
} as const;

export type CheckoutErrorCode = typeof CHECKOUT_ERRORS[keyof typeof CHECKOUT_ERRORS];
